extends:
    - standard
    - plugin:react/recommended

env:
    browser: true
    commonjs: true
    es6: true

plugins: ["react"]

parserOptions:
    ecmaVersion: 7
    sourceType: "module"
    ecmaFeatures:
        jsx: true

rules:
    react/prop-types: 0
    react/react-in-jsx-scope: 0
