# Stylelint Config
#
# @author Roelof Roos

extends: stylelint-config-standard

plugins:
  - stylelint-scss
  - stylelint-declaration-strict-value

# And add some of our rules
rules:
  # NEVER write vendor prefixes, Autoprefixer will take care of that
  value-no-vendor-prefix: true

  # Enure lowercase everything
  property-case: lower
  selector-pseudo-class-case: lower
  selector-type-case: lower
  selector-pseudo-element-case: lower
  media-feature-name-case: lower
  at-rule-name-case: lower
  color-hex-case: lower
  function-name-case: lower
  unit-case: lower
  value-keyword-case: lower

  # Furthermore, restrict colour definitions
  color-hex-length: long
  color-named: never
  color-no-invalid-hex: true

  # And to keep things simple, just use `.2` to write decimal digits, not `0.2`
  number-leading-zero: never

  # And make sure all resources are loaded explicitly over https, or are local
  function-url-no-scheme-relative: true
  function-url-scheme-whitelist: ['data', 'https']

  # Allow some newlines between blocks
  declaration-empty-line-before:
    - never
    - ignore:
      - after-declaration

  # And /never/ allow important
  keyframe-declaration-no-important: true
  declaration-no-important: true

  # Finally, cut some slack on @-rules for all Sass methods.
  at-rule-no-unknown:
    - true
    - ignoreAtRules: &sass-rules
      - content
      - else
      - error
      - extend
      - function
      - if
      - import
      - include
      - mixin
      - return
  at-rule-empty-line-before:
    - always
    - ignoreAtRules: *sass-rules

  # Force to use variables on a lot of colour elements
  scale-unlimited/declaration-strict-value:
    - /-color$/
    - color
    - /font-(family|weight)/
