language: php
php:
  - '7.1'
  - nightly

services:
    - mysql
    - redis

cache:
    directories:
        - /home/travis/.composer
        - vendor/
        - node_modules/

env:
    - SYMFONY_ENV=test

# Create testing database and user
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS symfony_test;'
  - mysql -e 'GRANT ALL ON symfony_test.* TO travis;'
  - composer global require squizlabs/php_codesniffer --no-suggest
  - 'export PATH="${PATH}:${HOME}/.composer/vendor/bin"'

before_script:
    - composer install --no-suggest
    - php bin/console doctrine:schema:create --dump-sql

script:
    - phpunit
    - phpcs -n
