version: '2.2'

volumes:
  mysql-data:
  redis-data:

networks:
  gotcha:
    driver: bridge

services:
  redis:
    image: redis:4-alpine
    hostname: redis.assassin.local
    networks:
      - gotcha
    ports:
      - "127.13.37.1:6379:6379"
    volumes:
      - redis-data:/data

  mysql:
    image: mariadb
    hostname: mysql.assassin.local
    networks:
      - gotcha
    ports:
      - "127.13.37.1:3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

      # The Docker MySQL isn't publicly visible (it's linked to a link-local
      # address after all), there's no real need to be very secure about
      # these passwords.
      MYSQL_DATABASE: assassin
      MYSQL_USER: assassin_usr
      MYSQL_PASSWORD: tiemu7waf4Zei7eit0eive7Mee8quah2
