<?php

namespace AppBundle\Repository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find all games owned by the given host.
     *
     * @param  User         $host
     * @param  array|null   $orderBy
     * @param  int|null     $limit
     * @param  int|null     $offset
     * @return array
     */
    public function findByHost(User $host, array $orderBy = null, $limit = null, $offset = null)
    {
        $orderBy = $orderBy ?? ['alias' => 'ASC'];

        return $this->findBy([
            'host' => $host
        ], $orderBy, $limit, $offset);
    }
}
