<?php
declare(strict_types=1);

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HitRepository extends EntityRepository
{
    /**
     * Returns the newest hit first
     * @var string
     */
    const ORDER_NEWEST_FIRST = 'DESC';

    /**
     * Returns the oldest hit first
     * @var string
     */
    const ORDER_OLDEST_FIRST = 'ASC';

    /**
     * Find all hits for a given player, which is always limited to a certain
     * game.
     *
     * @param  Player       $player
     * @param  string|null  $sortOrder
     * @param  int|null     $limit
     * @param  int|null     $offset
     * @return array
     */
    public function findHitsByPlayer(
        Player $player,
        string $sortOrder = null,
        int $limit = null,
        int $offset = null
    ) : array {
        return $this->findBy(
            ['assassin' => $player],
            ['date' => $sortOrder ?? self::ORDER_NEWEST_FIRST],
            $limit,
            $offset
        );
    }

    /**
     * Find all deaths for a given player, which is always limited to a certain
     * game. This usually returns no results, or one, but if a hit is
     * disapproved, it returns multiple.
     *
     * @param  Player       $player
     * @param  string|null  $sortOrder
     * @param  int|null     $limit
     * @param  int|null     $offset
     * @return array
     */
    public function findDeathsByPlayer(
        Player $player,
        string $sortOrder = null,
        int $limit = null,
        int $offset = null
    ) : array {
        return $this->findBy(
            ['target' => $player],
            ['date' => $sortOrder ?? self::ORDER_NEWEST_FIRST],
            $limit,
            $offset
        );
    }

    /**
     * Find all hits in a game, may return an empty array.
     *
     * @param  Game         $game
     * @param  string|null  $sortOrder
     * @param  int|null     $limit
     * @param  int|null     $offset
     * @return array
     */
    public function findByGame(
        Game $game,
        string $sortOrder = null,
        int $limit = null,
        int $offset = null
    ) : array {
        return $this->findBy(
            ['game' => $game],
            ['date' => $sortOrder ?? self::ORDER_NEWEST_FIRST],
            $limit,
            $offset
        );
    }
}
